services:
  smartflow-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: smartflow-backend
    platform: linux/arm64
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGGER_URL=http://seq:5341
      - ConnectionStrings__Postgres_Connection=Host=postgres;Port=5432;Database=smartflow;Username=smartech;Password=Stt@1234
    depends_on:
      postgres:
        condition: service_healthy
      seq:
        condition: service_started
    restart: unless-stopped
    networks:
      - smartflow-networks

  seq:
    image: datalust/seq:2024.1
    container_name: smartflow-seq
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "7878:80"
    volumes:
      - ./seq/log:/data
    restart: unless-stopped
    networks:
      - smartflow-networks

  postgres:
    image: postgres:15
    container_name: smartflow-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartech -d smartflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: smartech
      POSTGRES_PASSWORD: Stt@1234
      POSTGRES_DB: smartflow
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    networks:
      - smartflow-networks

volumes:
  postgresql_data:

networks:
  smartflow-networks:
    driver: bridge