services:
  smartflow-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: smartflow-backend
    platform: linux/arm64
    ports:
      - "2000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGGER_URL=http://logger-seq:80
      - ConnectionStrings__Postgres_Connection=Host=smartflow-db;Port=5432;Database=SmarTechTeam;Username=smartech;Password=Stt@1234
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=smartech
      - RABBITMQ_PASSWORD=Stt@1234
    depends_on:
      smartflow-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - identity-networks

  smartflow-db:
    image: postgres:15
    container_name: smartflow-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartech -d SmarTechTeam"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: smartech
      POSTGRES_PASSWORD: Stt@1234
      POSTGRES_DB: SmarTechTeam
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "3000:5432"
    networks:
      - identity-networks

volumes:
  postgresql_data:

networks:
  identity-networks:
    external: true
    driver: bridge